### ISSUE TITLE
Update package-lock.json

### ISSUE THREAD

**Issue by matthewnau** [matthewnau/libmoji#8]
@willdavidow what do I need to update in the package-lock.json for version 2.1.2? I have not worked with this before. Your insight is greatly appreciated! This should be the last thing that needs to be updated before publishing to npm.

**Comment by willdavidow** [comment]
@matthewnau I believe all that would have changed in that file is the `version` since no new packages were added/updated. 

The file itself is auto-generated/maintained by `npm` operations, so I don't know that you have to manually/directly do anything to it... It was generated back when I submitted #6 after installing BabelJS. I haven't made any direct changes to it.

`package-lock.json` is `npm`'s way of attempting to normalize how multiple people working across a project install dependencies, with the goal of us all running the same versions of various project dependencies.

https://docs.npmjs.com/files/package-lock.json

As for publishing to `npm`/bumping the version number - are you doing that manually or using [np](https://github.com/sindresorhus/np) (or something like it?). I want to say that using `np` to handle versioning would modify both `package.json` and `package-lock.json`'s version numbers in sync and you won't have to touch either file.

**Comment by matthewnau** [comment]
@willdavidow Ok. I've been using the standard npm publish, but I'll look into using np to help make that process better. Thanks!
